
__all__ = [
    'TYPE_CHECKING',
    'ENCODING',
    'BYTEORDER',

    '__ROOT__',
    '__INTERNAL__',
    '__PLATFORM__',
    '__IMPORTER__',
]


from typing import TYPE_CHECKING as TYPE_CHECKING, Literal
from types import FrameType


class _PlatformInformation:
    __slots__ = (
        'system',
        'win32',
        'linux',
        'mac',
        'jython',
        'type',
        'id',
        'linkage',
        'version',
        'is64bit',
        'is32bit',
    )

    def __init__(self, *args, **kwargs):
        self.system: str = ...
        self.win32: bool = ...
        self.linux: bool = ...
        self.mac: bool = ...
        self.jython: bool = ...
        self.type: str = ...
        self.id: str = ...
        self.linkage: str = ...
        self.version: tuple = ...
        self.is64bit: bool = ...
        self.is32bit: bool = ...


ENCODING: str = ...
BYTEORDER: Literal['big', 'little'] = ...

__ROOT__: str = ...
__INTERNAL__: str = ...
__PLATFORM__: _PlatformInformation = ...
__IMPORTER__: FrameType | None = ...

